source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Picke' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge',
    'DevSupport'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  # pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../node_modules/react-native-maps/'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'  # <~~ if you need GoogleMaps support on iOS


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-safari-view', :path => '../node_modules/react-native-safari-view'


  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "react-native-google-maps"
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
    end
end
